# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QsxQ3IQcnkcpnVDWsdXtDwApC85nyG01
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import sqlite3
import re
import numpy as np

# --- 1. CONFIGURATION & CONSTANTS ---
BASE_URL = "http://books.toscrape.com/catalogue/category/books"
# Targeting 3 specific categories to easily exceed 60 books
CATEGORIES = {
    "Mystery": f"{BASE_URL}/mystery_3/index.html",
    "Historical Fiction": f"{BASE_URL}/historical-fiction_4/index.html",
    "Sequential Art": f"{BASE_URL}/sequential-art_5/index.html"
}
GBP_TO_INR_RATE = 105.50
DB_NAME = "zepto_catalog.db"

# --- 2. EXTRACTION (SCRAPING) ---
def scrape_books():
    """Scrapes book data from the targeted categories."""
    books_data = []

    for category_name, url in CATEGORIES.items():
        current_url = url

        while current_url:
            response = requests.get(current_url)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, 'html.parser')

            articles = soup.find_all('article', class_='product_pod')
            for article in articles:
                title = article.h3.a['title']
                price_text = article.find('p', class_='price_color').text
                rating_class = article.find('p', class_='star-rating')['class'][1]
                availability = article.find('p', class_='instock availability').text.strip()

                books_data.append({
                    'title': title,
                    'price_raw': price_text,
                    'rating_raw': rating_class,
                    'availability_raw': availability,
                    'category': category_name
                })

            # Pagination handling
            next_btn = soup.find('li', class_='next')
            if next_btn:
                next_page = next_btn.a['href']
                current_url = current_url.rsplit('/', 1)[0] + '/' + next_page
            else:
                current_url = None

    return pd.DataFrame(books_data)

# --- 3. TRANSFORMATION (CLEANING) ---
def clean_data(df):
    """Cleans and properly types the raw scraped data."""
    # Mapping for star ratings
    rating_map = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}

    # 1. Strip currency symbol and convert to float
    # We use regex to extract the numeric part (ignoring the £ symbol)
    df['price_gbp'] = df['price_raw'].str.extract(r'(\d+\.\d+)').astype(float)

    # 2. Convert text star rating to integer
    df['rating'] = df['rating_raw'].map(rating_map).astype('Int64') # Int64 handles NaNs if any

    # 3. Parse availability text into boolean
    df['in_stock'] = df['availability_raw'].str.contains('In stock', case=False, na=False)

    # 4. Handle missing or unparseable data
    # Decision: Drop rows where critical catalog data (price or title) is missing.
    # Impute missing ratings with the median rating.
    df = df.dropna(subset=['title', 'price_gbp'])
    if df['rating'].isnull().any():
        median_rating = int(df['rating'].median())
        df['rating'] = df['rating'].fillna(median_rating)

    # 5. Enrich with fixed-rate currency conversion
    df['price_inr'] = df['price_gbp'] * GBP_TO_INR_RATE

    # Select final columns
    final_cols = ['title', 'price_gbp', 'price_inr', 'rating', 'in_stock', 'category']
    return df[final_cols]

# --- 4. LOADING (SQLITE DB) ---
def load_to_db(df, db_name):
    """Creates a normalized schema and loads the data."""
    conn = sqlite3.connect(db_name)
    cursor = conn.cursor()

    # Create Categories Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS categories (
            category_id INTEGER PRIMARY KEY AUTOINCREMENT,
            category_name TEXT UNIQUE NOT NULL
        )
    ''')

    # Create Books Table (with Foreign Key)
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS books (
            book_id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            price_gbp REAL NOT NULL,
            price_inr REAL NOT NULL,
            rating INTEGER NOT NULL,
            in_stock BOOLEAN NOT NULL,
            category_id INTEGER,
            FOREIGN KEY (category_id) REFERENCES categories (category_id)
        )
    ''')

    # Insert unique categories
    categories = df[['category']].drop_duplicates()
    categories.to_sql('categories_temp', conn, if_exists='replace', index=False)
    cursor.execute('''
        INSERT OR IGNORE INTO categories (category_name)
        SELECT category FROM categories_temp
    ''')

    # Get category IDs back and merge with books data
    cat_df = pd.read_sql('SELECT * FROM categories', conn)
    df_merged = df.merge(cat_df, left_on='category', right_on='category_name')

    # Insert Books
    books_to_insert = df_merged[['title', 'price_gbp', 'price_inr', 'rating', 'in_stock', 'category_id']]
    books_to_insert.to_sql('books', conn, if_exists='replace', index=False)

    conn.commit()
    return conn

# --- 5. QUERYING & VALIDATION ---
def execute_queries(conn):
    """Executes required SQL queries and performs pandas vs SQL validation."""

    queries = {
        "1. SELECT/WHERE": "SELECT title, price_gbp FROM books WHERE in_stock = 1 LIMIT 3;",
        "2. ORDER BY/LIMIT": "SELECT title, price_inr FROM books ORDER BY price_inr DESC LIMIT 3;",
        "3. DISTINCT": "SELECT DISTINCT rating FROM books;",
        "4. IN / BETWEEN": "SELECT title, rating FROM books WHERE rating IN (4, 5) AND price_gbp BETWEEN 10 AND 20 LIMIT 3;",
        "5. JOIN": """
            SELECT c.category_name, b.title, b.rating
            FROM books b
            JOIN categories c ON b.category_id = c.category_id
            WHERE b.rating = 5
            LIMIT 5;
        """
    }

    print("\n--- SQL QUERY RESULTS ---")
    for name, query in queries.items():
        print(f"\n{name}:\n{query}")
        result = pd.read_sql(query, conn)
        print(result.to_string(index=False))

    print("\n--- PANDAS VS SQL JOIN COMPARISON ---")

    # 1. Execute Join via SQL
    sql_join_query = """
        SELECT c.category_name, b.title, b.rating
        FROM books b
        JOIN categories c ON b.category_id = c.category_id
        WHERE b.rating = 5
    """
    df_sql_join = pd.read_sql(sql_join_query, conn)

    # 2. Execute equivalent Join via Pandas
    df_books = pd.read_sql("SELECT * FROM books", conn)
    df_categories = pd.read_sql("SELECT * FROM categories", conn)

    df_pandas_join = pd.merge(
        df_books,
        df_categories,
        on='category_id',
        how='inner'
    )
    # Filter for rating = 5 and select the exact same columns
    df_pandas_join = df_pandas_join[df_pandas_join['rating'] == 5][['category_name', 'title', 'rating']]

    # Compare
    print("\nSQL Output (First 3 rows):")
    print(df_sql_join.head(3).to_string(index=False))
    print("\nPandas Output (First 3 rows):")
    print(df_pandas_join.head(3).to_string(index=False))

    # Assert equivalence (resetting index to ensure clean comparison)
    is_equal = df_sql_join.sort_values('title').reset_index(drop=True).equals(
        df_pandas_join.sort_values('title').reset_index(drop=True)
    )
    print(f"\nDo the SQL and Pandas join outputs match exactly? -> {is_equal}")

if __name__ == "__main__":
    print("Extracting data...")
    raw_df = scrape_books()
    print(f"Scraped {len(raw_df)} books.")

    print("Transforming data...")
    clean_df = clean_data(raw_df)

    print("Loading to SQLite DB...")
    db_conn = load_to_db(clean_df, DB_NAME)

    execute_queries(db_conn)
    db_conn.close()